  docker-build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.barau16 }}
          password: ${{ secrets.dckr_pat_JuD_hkBV3v9hV0rVnyrbb3ScFI8 }}

      - name: Build and push Docker image (push only)
        if: github.event_name == 'push'
        run: |
          docker build -t ${{ secrets.barau16 }}/flaskapp:latest .
          docker push ${{ secrets.barau16 }}/flaskapp:latest

      - name: Build Docker image (PR only)
        if: github.event_name == 'pull_request'
        run: |
          docker build -t flaskapp .
